sudo: required
language: go
go:
- 1.13.x
script:
- make fmt
- make test
- make dist
- "./ci/hashgen.sh"
deploy:
  provider: releases
  api_key:
    secure: CDtRwdyt06F0olFaYqxeyPmiTmHxPiBg9v5AW3d0IP3yOYyQi1/NPFZf8Ix3ZgEElkmWqL2scyfaCUdwR5Yl1VQ1UUQd1xM37+BcMGtJ+AMir0jE4QIylQWaWUh0wj/S9m19/wmY+SlHdheCZsz3QBXOE4MwfAdJrLaUZfCWAKlLzRiaWABBy1/zM1zgD85u5MbBS4oHO0kap6dY/sdhcAxM+oI9Bu2HY912yhx0zmaTSN6wfO47F81EAqHLVaISdCbBu5+T0AxVaJFSZKkqk0nnROdQxTlgzl0nYBdBE+RASWUA2Uyn71DEprbU2zC/JdF1Wga8Bcm57XZRENqg5H8zi60J7dDf8ZAkvQ9k2m/GwjPyNcCTzE5sRD9dJKYQH9QWpDh2oeniOMrvak7btT6bKNnwhswbi5cgR5402aaNoEgTFrpTehKjAaIguDwoB4YY7gSSIwrsY9hsagmZhgwYp3ppt0D7bacHhrumHnPgrNsiSrZ3SC6t4PcpOe7zrAGT6ipm2bKg92JBvY5mHUirc5St/PBUzGeEr5X404QLInjPEPJeCsgI4kceQDN4KFjUZFGx1pjdbmdQAvCO85OyUhhsBKe0OqWcoJ5RzeCppTbISP/m+N+b9ulutbrpksyJGz8WVAXexWE1l5zgatF2Hed6h9xHN+mbTv1wCpk=
  prerelease: false
  overwrite: true
  file: 
  - bin/arkade
  - bin/arkade-arm64
  - bin/arkade-armhf
  - bin/arkade-darwin
  - bin/arkade.exe
  - bin/arkade.sha256
  - bin/arkade-arm64.sha256
  - bin/arkade-armhf.sha256
  - bin/arkade-darwin.sha256
  - bin/arkade.exe.sha256

  skip_cleanup: true
  on:
    tags: true

env: GO111MODULE=on
