name: check-tools-upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
    check-url:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
          with:
            fetch-depth: 1
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.17
        - name: Check tools URL
          run: make check
